### ISSUE TITLE
`overrideLoopMode` can't be set to false

### ISSUE THREAD

**Issue by MadBrot** [wizpanda/super-gif#4]
Beacuse of ` this.overrideLoopMode = opts.loopMode || 'auto'` if the option loopMode is set to false it will use 'auto'. Parsing false as a string also doesn't work beacuse of the hart comparison `this.overrideLoopMode !== false `

Same happens with `drawWhileLoading` just that its always true.

**Comment by MadBrot** [comment]
By changing `opts.loopMode || 'auto'` to `opts.loopMode ?? 'auto'` it works, as the `??` operator takes the right side if left side is `null`

**Comment by sagrawal31** [comment]
A PR would be appreciated.

**Comment by jianquan-testdome** [comment]
@sagrawal31 Could you please update the package for the fix? Thank you!

**Comment by sagrawal31** [comment]
Version 0.0.6 released with the fix.
